export const queryParamsMap = {
  page: "page",
  itemsPerPage: "itemsPerPage",
  properties: "properties",
  datumBefore: "datum[before]",
  datumStrictlyBefore: "datum[strictly_before]",
  datumAfter: "datum[after]",
  datumStrictlyAfter: "datum[strictly_after]",
  krajNutsKod: "kraj_nuts_kod",
  krajNazev: "kraj_nazev",
  okresLauKod: "okres_lau_kod",
  okresNazev: "okres_nazev",
  vekBetween: "vek[between]",
  vekGt: "vek[gt]",
  vekGte: "vek[gte]",
  vekLt: "vek[lt]",
  vekLte: "vek[lte]",
} as { [key: string]: string };
