name: On Push

on:
  push:
    branches:
      - '**' 

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout/@v4
        with:
          repository: radekBednarik/covid-czech-data-api
          token: ${{secrets.PAT_ALLOW_WF_MOD}}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x:w


      - name: Format
        run: deno fmt

      - name: Commit format changes if any
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m 'cicd(no-push): apply deno fmt changes'
            git push
          else
            echo "No changes to commit"
          fi
